# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Emmanuel Pellegrin
title: Data Scientist (student), Senior BI Consultant
email: git@pellegrin.me
website: www.pellegrin.me

# Social links
twitter_username: e_pellegrin
github_username:  mordor-ai
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: emmanuel.pellegrin
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Emmanuel and I'm a part-time Data Scientist student and Business Intelligence Consultant. I'As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data science and busienss intelligence some of my other interests and hobbies are:
   - Kite-surfing
   - Swimming
   - tasting wine
   - my family , including my (cat)[images/chachou.jpeg] 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
